sonar.verbose=true
sonar.organization=siva
sonar.projectKey=siva-vipparla_hani
sonar.projectName=hani
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
